[build]
  base = "client"
  publish = "client/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  VITE_API_BASE_URL = "https://your-backend-url.railway.app/api"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://your-backend-url.railway.app/api"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://your-backend-url.railway.app/api"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
